# Project-wide Gradle settings.

# JVM arguments for the daemon process
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Parallel builds
# org.gradle.parallel=true

# AndroidX - ENABLED
android.useAndroidX=true

# Jetifier - converts old support libs to AndroidX
android.enableJetifier=true

# Non-final resource IDs
android.nonFinalResIds=false
